project/website/models.py
from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    birth_date = db.Column(db.DateTime)
    role = db.Column(db.String(10))
    seats = db.relationship('Seat')


class Seat(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    seat_flight = db.Column(db.String(10))
    seat_row = db.Column(db.String(5))
    seat_column = db.Column(db.String(5))
    seat_status = db.Column(db.String(10))
    seat_type = db.Column(db.String(10))
    seat_unique = db.Column(db.String(20), unique=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

project/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from os import path

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    """Creates the webserver and the database"""
    from .views import views
    from .auth import auth
    from .admin import admins
    from .models import User, Seat
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(admins, url_prefix='/admin-area')
    db.init_app(app)
    create_database(app)

    # The LogingManager verifies if the current user is logged in
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    return app


def create_database(app):
    """Creates the database which contains the classes User and Seats"""
    if not path.exists('website/' + DB_NAME):
        app = Flask(__name__)
        app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
        db.init_app(app)
        with app.app_context():
            db.create_all()
    return app

project/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from .models import User, Seat
from .Statistics import database_reader
from . import db

from .python_scripts import new_user_checker

auth = Blueprint('auth', __name__)


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    """Creates the sign-up pages on which new users can log in."""
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        birth_date = request.form.get('birth_date')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        role = 'user'
        user_to_check = new_user_checker(email, first_name, last_name, birth_date, password1, password2)

        # if the user check is passed a new user will be added to the user-database and logged in.
        if user_to_check:
            birth_date = datetime.strptime(birth_date, '%Y-%m-%d')
            new_user = User(email=email, first_name=first_name, last_name=last_name, birth_date=birth_date,
                            password=generate_password_hash(password1, method='sha256'), role=role)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')

            return redirect(url_for('views.home'))
    return render_template("sign_up.html", user=current_user)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    """Creates the login page on which the users where the user can log in."""
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, please try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    """Logs the user out and ends the session.After logging out the user will be redirected to the login page."""
    logout_user()
    database_reader(Seat)
    flash('Logged out successfully! Thank you for traveling with Snakes on a Plane!!', category='success')
    return redirect(url_for('auth.login'))

project/website/views.py
from flask import Blueprint, render_template, flash, redirect
from flask_login import login_required, current_user
from .models import Seat
from . import db

views = Blueprint('views', __name__)


@views.route('/', methods=['GET'])
@login_required
def home():
    """Creates the home page of the website."""
    return render_template("home.html", user=current_user)


@views.route('/bookingsystem', methods=['GET'])
@login_required
def bookingsystem():
    """Creates the booking-system page where users can choose the flight they want to book a seat on."""
    flights = Seat.query.filter_by(seat_row='1', seat_column='A').all()
    return render_template('bookingsystem.html', user=current_user, flights=flights)


@views.route('/help', methods=['GET'])
@login_required
def help_page():
    """Creates the help page where users find information about how the booking-system works."""
    return render_template('help.html', user=current_user)


@views.route('/flight/<int:flights>', methods=['GET'])
@login_required
def flight(flights):
    """Creates the page where the seat layout of the previously chosen flight is displayed."""
    seat_to_render = Seat.query.filter_by(seat_flight=flights)
    row_number = Seat.query.filter_by(seat_flight=flights, seat_column='A').all()
    list_of_rows = []
    for i in range(len(row_number)+1):
        row = Seat.query.filter_by(seat_flight=flights, seat_row=i)
        list_of_rows.append(row)

    return render_template('seats.html', user=current_user, seat_to_render=seat_to_render, list_of_rows=list_of_rows)


@views.route('/flight/<int:flights>/booking-seat/<int:id>', methods=['GET'])
@login_required
def booking_seat(flights, id):
    """Lets user book a seat when clicking on it and confirming their choice."""
    booked_seat = Seat.query.get_or_404(id)
    booked_seat.seat_status = 'False'
    booked_seat.user_id = current_user.id
    try:
        db.session.commit()
        flash('Seat booked successfully!', category='success')
    except:
        flash('An error occurred while booking your seat', category='error')
    return redirect('/flight/'+str(flights))


@views.route('/flight/<int:flights>/cancel-seat/<int:id>', methods=['GET'])
@login_required
def cancel_seat(flights, id):
    """Lets user cancel the reservation of a seat by clicking on it and confirming the cancellation."""
    canceled_seat = Seat.query.get_or_404(id)
    canceled_seat.seat_status = 'True'
    canceled_seat.user_id = 'None'
    try:
        db.session.commit()
        flash('Seat canceled successfully!', category='success')
    except:
        flash('An error occurred while canceling your seat', category='error')
    return redirect('/flight/'+str(flights))

project/website/templates/admin_seats.html
{% extends "base.html" %} {% block title %}Admin{% endblock %}
{% block content%}
<h1 align="center">Admin Page</h1>
<h2 align="center">Seats</h2>
<form method="POST" align="center">
<a class="btn btn-primary link" href="/admin-area/update-flights" >Update Seats</a>
</form>
<br>
<table class="table table-striped" id="users">
    <thead>
        <tr>
        <th scope="col">ID</th>
        <th scope="col">Flight</th>
        <th scope="col">Row</th>
        <th scope="col">Seat</th>
        <th scope="col">Status</th>
        <th scope="col">Type</th>
        <th scope="col">User</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for seat in seats %}
        <tr>
        <td>{{seat.id}}</td>
        <td>{{seat.seat_flight}} </td>
        <td>{{seat.seat_row}}</td>
        <td>{{seat.seat_column}}</td>
        <td>{{seat.seat_status}}</td>
        <td>{{seat.seat_type}}</td>
        <td>{{seat.user_id}}</td>
        <td><a class="icon" href="{{url_for('admins.update_seat', id=seat.id)}}" >
            <span class="fa fa-pencil glyphicon glyphicon-pencil"></span></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

project/website/templates/admin_statistic.html
{% extends "base.html" %}
{% block title %}Admin{% endblock %}

{% block content%}
<h1 align="center">Admin Page</h1>
<h3 align="center">Statistic for flight {{flight}}</h3>
<form method="POST">
<div class="container" align="center">
    <a class="btn btn-primary link" href="/admin-area/refresh-statistics" >Refreshing Statistics File</a>
    <button class="btn btn-info dropdown dropdown-toggle" type="button" id="flightmenu" data-toggle="dropdown">Statistics for flights
     <span class="caret"></span></button>
     <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
     {% for seat in flights %}
     <li role="presentation">
     <a role="menuitem" tabindex="-1" href="{{url_for('admins.admin_flight_statistic', flight=seat.seat_flight)}}"> Statistic for flight{{seat.seat_flight}}</a></li>
     {% endfor %}
     </ul>
</div>
<br>
<br>
<div class="container" align="center">
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js'
    ></script>
    <canvas id="chart" width="600" height="400"></canvas>
    <script>
      var pieData = [
        {% for item, label, colors in set %}
          {value: {{item}},
          label: "{{label}}",
          color : "{{colors}}"
          },
        {% endfor %}
      ];

      // draw pie chart
      new Chart(document.getElementById("chart").getContext("2d")).Pie(pieData);
    </script>
</div>
</form>
{% endblock %}

project/website/templates/admin_statistics.html
{% extends "base.html" %}
{% block title %}Admin{% endblock %}

{% block content%}
<h1 align="center">Admin Page</h1>
<h3 align="center">Statistics.</h3>
<form method="POST" align="center">
<a class="btn btn-primary link" href="/admin-area/refresh-statistics" >Refreshing Statistics</a>
</form>
{% endblock %}

project/website/templates/admin_update_seat.html
{% extends "base.html" %} {% block title %}Updating Seat{% endblock %}
{% block content %}
<form action="/admin-area/seats/update-seats/{{seat_to_update.id}}" method="POST">
  <h3 align="center">Update Seat </h3>
  <h4 align="center">Flight: {{seat_to_update.seat_flight}} Row: {{seat_to_update.seat_row}} Seat: {{seat_to_update.seat_column}} </h4>
  <div class="form-group">
    <label for="user_id">User_ID ("None" or empty for free seat)</label>
    <input
      type="text"
      class="form-control"
      id="user_id"
      name="user_id"
      value="{{ seat_to_update.user_id }}"
    />
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

project/website/templates/admin_update_user.html
{% extends "base.html" %} {% block title %}Updating User{% endblock %}
{% block content %}
<form action="/admin-area/user/update-user/{{user_to_update.id}}" method="POST">
  <h3 align="center">Update User</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      value="{{ user_to_update.email }}"
    />
  </div>
  <div class="form-group">
    <label for="first_name">First Name</label>
    <input
      type="text"
      class="form-control"
      id="first_name"
      name="first_name"
      value="{{ user_to_update.first_name }}"
    />
  </div>
  <div class="form-group">
    <label for="last_name">Last Name</label>
    <input
      type="text"
      class="form-control"
      id="last_name"
      name="last_name"
      value="{{ user_to_update.last_name }}"
    />
  </div>
  <div class="form-group">
    <label for="role">Role</label>
    <select id="role" name="role" class="form-control">
     <option id="role" name="role" value="user">User</option>
     <option id="role" name="role" value="admin" >Admin</option>
    </select>
    </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

project/website/templates/admin_user.html
{% extends "base.html" %} {% block title %}Admin{% endblock %}
{% block content%}
<h1 align="center">Admin Page</h1>
<h2 align="center">Users</h2>
<table class="table table-striped" id="users">
    <thead>
        <tr>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Date of Birth</th>
        <th scope="col">Email</th>
        <th scope="col">Role</th>
        <th scope="col">Seats</th>
        <th scope="col"></th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
        <td>{{user.first_name}}</td>
        <td>{{user.last_name}} </td>
        <td>{{user.birth_date}}</td>
        <td>{{user.email}}</td>
        <td>{{user.role}}</td>
        <td>{{user.seats}}</td>
        <td><a class="icon" href="{{url_for('admins.update_user', id=user.id)}}" >
            <span class="fa fa-pencil glyphicon glyphicon-pencil"></span></a></td>
        <td><a class="icon" href="{{url_for('admins.delete_user', id=user.id)}}">
            <span class="fa fa-trash glyphicon glyphicon-trash"></span>
        </a></td>
        </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock %}

project/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Requierd meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"/>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"/>
    <!-- Tab Title -->
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <img src="{{url_for('static',filename='img/SoaP_Logo1.svg')}}"  width="50" height="50">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav" role="tablist">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="bookingsystem" href="/bookingsystem">Booking System</a>
            {% if current_user.role == 'admin' %}
            <a class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="admin-area">Admin Area</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" id="admin-user" href="/admin-area/user">User</a>
                  <a class="dropdown-item" id="admin-seats" href="/admin-area/seats">Seats</a>
                  <a class="dropdown-item" id="admin-statistics" href="/admin-area/statistics">Statistics</a>
                </div>
            </a>
            {% endif %}
          <a class="nav-item nav-link" id="help" href="/help">Help</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- Block for modal -->
    {% block modal %}{% endblock %}
    <!-- Alert Messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <!-- Main Block -->
    <div class="container">{% block content %} {% endblock %}</div>
    <!-- JavaScript for Bootstrap-->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

project/website/templates/bookingsystem.html
{% extends "base.html" %} {% block title %}Bookingsystem{% endblock %}
{% block content%}
<form method="POST">
  <h1 align="center">Booking System</h1>
   <h3 align="center">Please choose your flight to continue your seat reservation. </h3>
  <br>
  <div class="dropdown" align="center">
    <button class="btn btn-info dropdown-toggle" type="button" id="flightmenu" data-toggle="dropdown">Flights
    <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
      {% for seat in flights %}
      <li role="presentation"><a role="menuitem" tabindex="-1" href="{{url_for('views.flight', flights=seat.seat_flight)}}">Flight{{seat.seat_flight}}</a></li>
      {% endfor %}
    </ul>
  </div>
  <div>
  <p align="center">Need help with your seat reservation? Click
	<a href="/help" class="link-primary">here </a>
	to get to our help page. </p>
  </div>
{% endblock %}
</form>

project/website/templates/help.html
{% extends "base.html" %}
{% block title %}Help{% endblock %}

{% block content%}
<h1 align="center">Help</h1>
<h3>General</h3>
<p> Our navigation bar on top of the page helps you to navigate through our booking system. </p>
<ul>
    <li><strong>Home</strong>: This will direct you to our home page where you have access to our seat reservation
        system.
    </li>
    <li><strong>Booking System</strong>: This will give you direct access to our seat reservation system.
    </li>
    <li><strong>Help</strong>: Since you are on our help page you might have already found this button, which leads you
        to this help page. In case you want to come back, just press this button in the navigation bar.
    </li>
    <li><strong>Logout</strong>: When you press this button, you will be logged out of the system and redirected to our
        login page.
    </li>
</ul>
<h3>How can I reserve a seat?</h3>
<div style="text-align: justify">
<p> Navigate to our <a href="/bookingsystem" class="link-primary">booking system</a> page via the button in the
    navigation bar on top of the page or via the link on our <a href="/" class="link-primary">home page</a>.
    Afterwards, you can choose the flight, that you want to reserve a seat on, from the dropdown menu. Access the
    dropdown menu via pressing the button saying "Flights".
</p>
<p>After choosing your flight, a chart with all seats on the flight will be displayed. Blue seats are still available
    and can be reserved by clicking on them. You will be asked to confirm your choice of seat in a popup. Please confirm
    your reservation by clicking "Reserve seat" in the popup. If you no longer want to reserve the seat you have clicked
    on, simply close the popup and you can continue to reserve other seats. </p>
<p>A seat, that has been reserved by you, will be displayed in green. If you want to cancel the reservation of one of
    those seats, simply click on the respective seat. A popup will ask you to confirm the cancellation by clicking
    "Cancel seat". If you decide not to cancel the seat, just close the popup and the respective seat will still be
    reserved by you.</p>
<p>Red seats are already taken by other users, therefore you will not be able to reserve them. </p>
<p>Once you have finished your reservation, click on the "Logout" button in the navigation bar on top of the page, to
    leave our websites.</p>
</div>
{% endblock %}

project/website/templates/seats.html
{% extends "base.html" %} {% block title %}Seats{% endblock %}

{% block content%}
<form method="POST">
<h1 align="center">Seats</h1>
	<h3 align="center">Please choose the seat you want to reserve. </h3>
	<p align="center">Need help with your seat reservation? Click
	<a href="/help" class="link-primary">here </a>
	to get to our help page. </p>

	{% for element in list_of_rows %}
	<div class="container" align="center">
		{% for seat in element %}
		{% if seat.seat_column == 'A' %}
		<span class="btn btn-light active disabled" >{{seat.seat_row}}</span>
		{% endif %}

		<!-- checking for aisle seat -->
		{% if seat.seat_type == 'Aisle_Left' %}
		{% if seat.seat_status == 'True' %}
		<a type="button" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" data-toggle="modal" data-target="#ReserveModal{{seat.id}}" href="{{url_for('views.booking_seat', id=seat.id, flights=seat.seat_flight)}}">{{seat.seat_column}}</a>

		<!-- Begin Modal -->
		<div class="modal fade" id="ReserveModal{{seat.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  			<div class="modal-dialog" role="document">
    			<div class="modal-content">
      				<div class="modal-header">
        				<h5 class="modal-title" id="ReserveModalLabel{{seat.id}}">Reserve seat</h5>
        				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          				<span aria-hidden="true">&times;</span>
        				</button>
      				</div>
      				<div class="modal-body">
        				Do you want to reserve seat {{seat.seat_row}}{{seat.seat_column}}?
      				</div>
      				<div class="modal-footer">
        				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        				<a type="button" class="btn btn-primary" href="{{url_for('views.booking_seat', id=seat.id, flights=seat.seat_flight)}}">Reserve seat</a>
      				</div>
    			</div>
  			</div>
		</div>
		<!-- End Modal -->

		<button type="button" class="btn btn-outline-light" disabled></button>
		{% elif seat.user_id == current_user.id%}
		<a type="button" class="btn btn-success btn-lg active" role="button" aria-pressed="true" data-toggle="modal" data-target="#CancelModal{{seat.id}}" href="{{url_for('views.cancel_seat', id=seat.id, flights=seat.seat_flight)}}">{{seat.seat_column}}</a>

		<!-- Begin Cancel Modal -->
		<div class="modal fade" id="CancelModal{{seat.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  			<div class="modal-dialog" role="document">
    			<div class="modal-content">
      				<div class="modal-header">
        				<h5 class="modal-title" id="CancelModalLabel{{seat.id}}">Cancel seat</h5>
        				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          				<span aria-hidden="true">&times;</span>
        				</button>
      				</div>
      				<div class="modal-body">
        				Do you want to cancel seat {{seat.seat_row}}{{seat.seat_column}}?
      				</div>
      				<div class="modal-footer">
        				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        				<a type="button" class="btn btn-primary" href="{{url_for('views.cancel_seat', id=seat.id, flights=seat.seat_flight)}}">Cancel seat</a>
      				</div>
    			</div>
  			</div>
		</div>
		<!-- End Cancel Modal -->

		<button type="button" class="btn btn-outline-light" disabled></button>
		{% elif seat.seat_status == 'False' %}
		<a type="button" class="btn btn-danger btn-lg active" role="button" aria-pressed="true">{{seat.seat_column}}</a>
		<button type="button" class="btn btn-outline-light" disabled></button>
		{% endif %}

		<!-- checking for other requirements -->
		{% elif seat.seat_status == 'True' %}
		<a type="button" href="{{url_for('views.booking_seat', id=seat.id, flights=seat.seat_flight)}}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" data-toggle="modal" data-target="#ReserveModal{{seat.id}}">{{seat.seat_column}}</a>

		<!-- Begin Reservation Modal -->
		<div class="modal fade" id="ReserveModal{{seat.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  			<div class="modal-dialog" role="document">
    			<div class="modal-content">
      				<div class="modal-header">
        				<h5 class="modal-title" id="ReserveModalLabel{{seat.id}}">Reserve seat</h5>
        				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          				<span aria-hidden="true">&times;</span>
        				</button>
      				</div>
      				<div class="modal-body">
        				Do you want to reserve seat {{seat.seat_row}}{{seat.seat_column}}?
      				</div>
      				<div class="modal-footer">
        				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        				<a type="button" class="btn btn-primary" href="{{url_for('views.booking_seat', id=seat.id, flights=seat.seat_flight)}}">Reserve seat</a>
      				</div>
    			</div>
  			</div>
		</div>
		<!-- End Reservation Modal -->

		{% elif seat.user_id == current_user.id%}
		<a type="button" class="btn btn-success btn-lg active" role="button" aria-pressed="true" data-toggle="modal" data-target="#CancelModal{{seat.id}}" href="{{url_for('views.cancel_seat', id=seat.id, flights=seat.seat_flight)}}">{{seat.seat_column}}</a>

		<!-- Begin Cancel Modal -->
		<div class="modal fade" id="CancelModal{{seat.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  			<div class="modal-dialog" role="document">
    			<div class="modal-content">
      				<div class="modal-header">
        				<h5 class="modal-title" id="CancelModalLabel{{seat.id}}">Cancel seat</h5>
        				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          				<span aria-hidden="true">&times;</span>
        				</button>
      				</div>
      				<div class="modal-body">
        				Do you want to cancel seat {{seat.seat_row}}{{seat.seat_column}}?
      				</div>
      				<div class="modal-footer">
        				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        				<a type="button" class="btn btn-primary" href="{{url_for('views.cancel_seat', id=seat.id, flights=seat.seat_flight)}}">Cancel seat</a>
      				</div>
    			</div>
  			</div>
		</div>
		<!-- End Cancel Modal -->

		{% elif seat.seat_status == 'False' %}
		<a type="button" class="btn btn-danger btn-lg active" role="button" aria-pressed="true">{{seat.seat_column}}</a>
		{% endif %}
		{% endfor %}
		</div>
		<p> </p>
		{% endfor %}
	<p> </p>
{% endblock %}
</form>